### PR TITLE
Update print statements and other syntax to Python 3

### LINKED ISSUE #29: Python 3.x support?
Python 2.7 is being deprecated. Do you plan to migrate to 3.x any time soon?

### PR DESCRIPTION
**Pull request by justjosias**
This will resolve #29. 

TODO:
- [x] Fix bitwise operators (I really messed those up)
- [x] Migrate tests

### CODE REVIEW

**Comment by blake5634** [comment]
Thanks for working on it.  I guess some todo's remain?

**Comment by justjosias** [comment]
@blake5634 Yes. I got burned out after that first run. I'll work on the rest soon.

**Comment by justjosias** [comment]
I have a question. I see this code often: `print(>>f`, ...). What does `>>f` do exactly? It is not valid Python 3 code since there is only one argument to the bitwise operator instead of `a>>b` as is now required. I assume it is a shortcut for a shifting of one, but I wanted to be sure I got the semantics right before proceeding.

**Comment by blake5634** [comment]
@justjosias 
Python 2                                               Python 3
print(>>f, 'something to print')               print('something to print, file=f)

Thanks again!

**Comment by justjosias** [comment]
@blake5634 I made the last few changes and now the tests pass.

**Comment by justjosias** [comment]
I notice that there is some code not covered under tests or during the main execution. I will migrate that as well.

**Comment by justjosias** [comment]
@blake5634 This has been done for a while. If you'd like to take another look at it you can.

**Comment by blake5634** [comment]
WOw - sorry.   I've been quite busy with other things but I'll try testing ASAP.   Stay on my case!

**Pull request merged**
